version: '3.4'

services:
  elasticsearch:
    build:
      context: ./dockerfiles/elasticsearch
      dockerfile: Dockerfile
    
    networks:
      mr-plow:
        ipv4_address: 10.70.67.102
      
    volumes:
      - ..:/workspaces/mr-plow:cached

    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

networks:
  mr-plow:
    external: true
    
