version: '3.4'

services:
  mrplow:
    build:
      context: ./docker_compose/mrplow
      dockerfile: Dockerfile
    
    networks:
      vsmrplow:
        ipv4_address: 172.25.0.201
      
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
      - ~/.ssh:/home/vscode/.ssh:cached
      - ..:/workspaces/mr-plow:cached

    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"

networks: 
  vsmrplow:
    driver: bridge
    attachable: true
    ipam:
      config:
        - subnet: 172.25.0.0/24
    
